### ISSUE TITLE
关于训练集的问题

### ISSUE THREAD

**Issue by superluckyxhh** [feymanpriv/DELG#11]
您好，在我跑这个`logger.info("Constructing dataset from {}...".format(split))
        self._data_path, self._split = data_path, split`的时候， split显示‘train_list.txt’，可我下载的GLDv2中没有这个txt，请您帮忙解答下，感谢

**Comment by nthhiep** [comment]
Hi, I have the same question. I do not know where to get "train_list.txt", "test_list.txt" for oxford5k and paris6k.

**Comment by feymanpriv** [comment]
HI, the txt file is generated by myself and i will upload.

**Comment by aheng11** [comment]
I would like to ask where val_ist.txt is located or how to solve a problem that does not exist
