### ISSUE TITLE
Question about preparing a training data 

### ISSUE THREAD

**Issue by youxige** [feymanpriv/DELG#14]
Hello,@feymanpriv 
Thank you for sharing your code.  But I ran into some problems when trying to run your code.  I downloaded the GLDv2 data set and got JPG files and CSV files, but the train_list.txt file and val_list file mentioned in your code are missing.  What should I do with the GLDv2 data set to get the missing files to run your code.
I would be very grateful if you could tell me how to do it.

**Comment by feymanpriv** [comment]
OK，i will upload the train dataset file.

**Comment by aheng11** [comment]
I would like to ask where val_ist.txt is located or how to solve a problem that does not exist
