### ISSUE TITLE
Can you show me your dataset structure？

### ISSUE THREAD

**Issue by vodka95** [feymanpriv/DELG#3]
When i run this code，it tells me AssertionError: Data path '/home/y182202031/DELG-master/datasets/data/landmark' not found. So, can you show me your dataset structure?

Traceback (most recent call last):
  File "train_delg.py", line 23, in <module>
    main()
  File "train_delg.py", line 19, in main
    dist.multi_proc_run(num_proc=cfg.NUM_GPUS, fun=trainer.train_model)
  File "/home/y182202031/DELG-master/core/distributed.py", line 141, in multi_proc_run
    fun(*fun_args, **fun_kwargs)
  File "/home/y182202031/DELG-master/core/trainer.py", line 176, in train_model
    train_loader = loader.construct_train_loader()
  File "/home/y182202031/DELG-master/datasets/loader.py", line 50, in construct_train_loader
    drop_last=True,
  File "/home/y182202031/DELG-master/datasets/loader.py", line 27, in _construct_loader
    dataset = DataSet(data_path, split)
  File "/home/y182202031/DELG-master/datasets/commondataset.py", line 38, in __init__
    assert os.path.exists(data_path), "Data path '{}' not found".format(data_path)
AssertionError: Data path '/home/y182202031/DELG-master/datasets/data/landmark' not found

**Comment by berooo** [comment]
The structure is:
DELG-master/datasets/data/GLDv2

GLDv2 is the dir of GLDv2-clean

**Comment by vodka95** [comment]
Thanks! Got it！But the GLDv2 dataset is too large for my server, can i use a smaller one such as 'oxford building' to replace it?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "feymanpriv/DELG"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 下午2:50
收件人:&nbsp;"feymanpriv/DELG"<DELG@noreply.github.com&gt;;
抄送:&nbsp;"    蘼芜"<694589494@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [feymanpriv/DELG] Can you show me your dataset structure？ (#3)





 
The structure is:
 DELG-master/datasets/data/GLDv2
 
GLDv2 is the dir of GLDv2-clean

**Comment by berooo** [comment]
Oxford building and oxford building are more suitable for testing but not for training. But if you have to use it as a training dataset, you may need to modify some code in this project.发自我的华为手机-------- 原始邮件 --------发件人： vodka95 <notifications@github.com>日期： 2020年12月29日周二 傍晚5:10收件人： feymanpriv/DELG <DELG@noreply.github.com>抄送： berooo <1819246385@qq.com>, Assign <assign@noreply.github.com>主    题： Re: [feymanpriv/DELG] Can you show me your dataset structure？ (#3)

Thanks! Got it！But the GLDv2 dataset is too large for my server, can i use a smaller one such as 'oxford building' to replace it?



















------------------&nbsp;原始邮件&nbsp;------------------



发件人:                                                                                                                        "feymanpriv/DELG"                                                                                    <notifications@github.com&gt;;



发送时间:&nbsp;2020年12月29日(星期二) 下午2:50



收件人:&nbsp;"feymanpriv/DELG"<DELG@noreply.github.com&gt;;



抄送:&nbsp;"    蘼芜"<694589494@qq.com&gt;;"Author"<author@noreply.github.com&gt;;



主题:&nbsp;Re: [feymanpriv/DELG] Can you show me your dataset structure？ (#3)























 



The structure is:



 DELG-master/datasets/data/GLDv2



 



GLDv2 is the dir of GLDv2-clean

**Comment by vodka95** [comment]
&nbsp;Hi, When i try to use Oxford building and paris building dataset to test the model, it seems that i need three files like&nbsp;
GLOBAL_FEATURE_PATH='roxford5k512gem_delg_res50_3global.mat'
LOCAL_FEATURE_PATH='roxford5k__s512_localfea.pickle'
ASMK_SCORE_PATH='localfeatures/delg_asmk_6553.pkl'
then i turn to&nbsp;https://github.com/filipradenovic/revisitop&nbsp;to run the model. If i may be so bold, could you send me the three files?
I’d be grateful if you could help me.
Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "feymanpriv/DELG"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 晚上6:38
收件人:&nbsp;"feymanpriv/DELG"<DELG@noreply.github.com&gt;;
抄送:&nbsp;"    蘼芜"<694589494@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [feymanpriv/DELG] Can you show me your dataset structure？ (#3)





 Oxford building and oxford building are more suitable for testing but not for training. But if you have to use it as a training dataset, you may need to modify some code in this project.发自我的华为手机-------- 原始邮件 --------发件人： vodka95 <notifications@github.com&gt;日期： 2020年12月29日周二 傍晚5:10收件人： feymanpriv/DELG <DELG@noreply.github.com&gt;抄送： berooo <1819246385@qq.com&gt;, Assign <assign@noreply.github.com&gt;主    题： Re: [feymanpriv/DELG] Can you show me your dataset structure？ (#3) 
 Thanks! Got it！But the GLDv2 dataset is too large for my server, can i use a smaller one such as 'oxford building' to replace it? 
 
 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 
 发件人:                                                                                                                        "feymanpriv/DELG"                                                                                    <notifications@github.com&amp;gt;; 
 
 发送时间:&amp;nbsp;2020年12月29日(星期二) 下午2:50 
 
 收件人:&amp;nbsp;"feymanpriv/DELG"<DELG@noreply.github.com&amp;gt;; 
 
 抄送:&amp;nbsp;"    蘼芜"<694589494@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 
 主题:&amp;nbsp;Re: [feymanpriv/DELG] Can you show me your dataset structure？ (#3) 
 
 
 
 
 
 
 
 
 
 
 
   
 
 The structure is: 
 
  DELG-master/datasets/data/GLDv2 
 
   
 
 GLDv2 is the dir of GLDv2-clean

**Comment by superluckyxhh** [comment]
> The structure is:
> DELG-master/datasets/data/GLDv2
> 
> GLDv2 is the dir of GLDv2-clean

Hello.When I reviewed this repo.  There is `self._data_path, self._split = data_path, split` in DataSet class and split is 'train_list.txt' in debuger. But Train dataset GLDv2 has not such as the 'txt' files.  So I want to ask what wrong in my operations
