### ISSUE TITLE
where I can download the  pretrained model for TRAIN.WEIGHTS

### ISSUE THREAD

**Issue by guodata** [feymanpriv/DELG#4]
Hi, 
I am a newbie about DELG, where I can download the pretrained model for TRAIN.WEIGHTS

**Comment by guodata** [comment]
I try to use resnet50-19c8e357.pth downloaded by pytorch , but it use different module name from this program
Thanks for any advice

**Comment by MurrayC7** [comment]
@guodata Hi, do you figure out a way to train from any initial weights?

**Comment by feymanpriv** [comment]
@guodata @MurrayC7 Hi, the pretrained model is  from https://dl.fbaipublicfiles.com/pycls/dds_baselines/161235311/R-50-1x64d_dds_8gpu.pyth
