### ISSUE TITLE
License for the code

### ISSUE THREAD

**Issue by nhonth** [feymanpriv/DELG#5]
Thanks a lot for sharing your code. May I ask what is the license for the code?

I plan to run experiments with it and incorporate part of it into my own code.

Thanks.

-- Nhon

**Comment by feymanpriv** [comment]
Thanks for reminding. MIT License is OK.

**Comment by nhonth** [comment]
That's great. Thank you. If not too much trouble, could you also add a LICENSE file to the repository?
