### ISSUE TITLE
Is there any pre-trained model could be released?

### ISSUE THREAD

**Issue by MurrayC7** [feymanpriv/DELG#6]
Hi, @feymanpriv. Thank you for the graceful implementation!
I'd appreciate it if there could be any pre-trained model trained on GLDv2, with which I want to finetune my data :)

Thanks again.

**Comment by feymanpriv** [comment]
@MurrayC7 OK, I will upload the model recently.

**Comment by MurrayC7** [comment]
Get it from #4.  It is really helpful. Thanks a lot!
